images:
# Development
# - Testing
- name: Goss
  description: Easy docker health checks, /healthz endpoints, and container delays 
  provides:
  - goss
  - dgoss
  - egoss
  image: docker.io/envcli/goss:latest
  containerRuntimeAccess: true
  cache:
  - name: tmp
    directory: /cache/tmp
